apiversion: apps/v1
kind: Deployment
metadata:
name: app-deployment
spec:
replicas: 3
selector:
matchLabels:
app: cust-app
template:
metadata:
labels:
app: cust-app
spec:
containers:
name: cust-app-container
image: yuvaraj2807/deploymenttraining:latest
ports:
container Port: 80
